### ISSUE TITLE
undefined is not and object

### ISSUE THREAD

**Issue by milon87** [Yalantis/ReactNativeTemplate#3]
if I press login button getting this error

![simulator screen shot aug 16 2017 7 56 11 pm](https://user-images.githubusercontent.com/3435314/29366919-1b06bd02-82bd-11e7-9c81-c63c545732eb.png)

**Comment by KucherenkoIhor** [comment]
Hello, @milon87 !
Thank you for your feedback!
We made some changes, and we think that it solves your problem.
Please, check it out!
